### ISSUE TITLE
Project support

### ISSUE THREAD

**Issue by mbukosky** [underarmour/further-review#250]
Hi, I wanted to get an understand of the state of the project and its release cycle. It doesn't seem to be getting much love. I think further-review is a great idea but still very raw. I have created a 3 providers locally already and would love to give back. I just want to make sure this project is not dead, otherwise I might have to fork.

Love to hear your thoughts.

Thanks
Mike

**Comment by kjvalencik** [comment]
Mike, thanks for your support! This project is *not* dead. It an integral part of our internal SDLC and gets used many, many times a day. However, while we have improvements we would like to make, it is not currently a priority since it is meeting our needs.

Thanks again for submitting https://github.com/underarmour/further-review/pull/249. It just so happens that it landed at a bad time--while I was on vacation--and, frankly, I forgot to come back to it. I appreciate the reminder.

I am very interested in any additional features you have. One of the more interesting features I would to see is the ability to use Github reviews instead of comments.

**Comment by mbukosky** [comment]
Awesome, glad to hear. I'll submit some more features in the next few weeks, once I iron out the bugs.
